In [1]:
import pandas as pd

In [38]:
df = pd.read_csv("raw_data.csv")
df.head()

   id          name   age country   gender   income
0   1      John Doe  29.0     USA     Male  55000.0
1   1      John Doe  29.0     USA     Male  55000.0
2   2    Jane Smith   NaN  Canada   Female  62000.0
3   3          Alex   NaN     USA  Unknown  47000.0
4   4  Maria Garcia  34.0   Spain   Female      NaN

### Handle Missing Values

In [10]:
# Check Null values
print(df.isnull())             # check null values
print("\n", df.isnull().sum()) # count null values

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

 id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [11]:
# Drop Null values
print(df.dropna())       # drop rows
print(df.dropna(axis=1)) # drop columns

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0
    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [14]:
# Replace Null values
print(df.fillna(0))        # replace all null values
mean_age = df["age"].mean()
print(df["age"].fillna(mean_age)) # replace null values for a column

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0
0     29.00
1     29.00
2     32.75
3     32.75
4     34.00
5     27.00
6     45.00
7     38.00
8     29.00
9     32.75
10    31.00
Name: age, dtype: float64

In [16]:
# Forward Fill - Fill top neighbor value
print(df.ffill())

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [17]:
# Backward Fill - Fill bottom neighbor value
print(df.bfill())

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

### Handle Duplicate Values

In [20]:
# Check duplicate values
print(df.duplicated())
print("\n", df["country"].duplicated())

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

 0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool

In [24]:
# Drop duplicates
df1 = df.copy()
df1.drop_duplicates(inplace=True)  # Inplace is used to save changes
df1

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

### Handle DataTypes & date-time

In [25]:
# Check datatypes
df.dtypes

id           int64
name           str
age        float64
country        str
gender         str
income     float64
dtype: object

In [32]:
# Change datatypes
df1 = df.copy()
df1 = df1.fillna(0)
df1["age"] = df1["age"].astype("int64")
df1.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [37]:
# Change Date-Time
df2 = pd.read_csv("globalAirQuality.csv")[["timestamp", "city", "aqi"]]
print(df2.head(3))
print(df2["timestamp"].dtype)

df2["timestamp"] = pd.to_datetime(df2["timestamp"])
print(df2["timestamp"].dtype)

                    timestamp      city  aqi
0  2025-11-04 18:25:17.554219  New York  108
1  2025-11-04 19:25:17.554219  New York   90
2  2025-11-04 20:25:17.554219  New York   84
str
datetime64[us]

### Handle Strings

In [42]:
# Upper, Lower, Capitalize
print(df["country"].str.upper())
print("\n", df["country"].str.lower())
print("\n", df["country"].str.capitalize())

0        USA
1        USA
2     CANADA
3        USA
4      SPAIN
5      CHINA
6      INDIA
7        NaN
8        USA
9     MEXICO
10       USA
Name: country, dtype: str

 0        usa
1        usa
2     canada
3        usa
4      spain
5      china
6      india
7        NaN
8        usa
9     mexico
10       usa
Name: country, dtype: str

 0        Usa
1        Usa
2     Canada
3        Usa
4      Spain
5      China
6      India
7        NaN
8        Usa
9     Mexico
10       Usa
Name: country, dtype: str

In [44]:
# Split
df["name"].str.split(" ")

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [45]:
# Strip
df["name"].str.strip()

0         John Doe
1         John Doe
2       Jane Smith
3             Alex
4     Maria Garcia
5           Li Wei
6              NaN
7       Ahmed Khan
8       Rachel Lee
9      Carlos Ruiz
10     Emily Davis
Name: name, dtype: str

In [47]:
# Contains
df["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: country, dtype: bool