In [1]:
import pandas as pd

### Merging & Joining Data

In [2]:
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})
print(df_customers)

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})
print("\n", df_orders)

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Charlie
3            4     Dave

    order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [3]:
# Inner Join
pd.merge(df_customers, df_orders, on="customer_id")

   customer_id  name  order_id  amount
0            1  Adam       102     120
1            2   Bob       101     250
2            4  Dave       103     300

In [4]:
# Left Join
pd.merge(df_customers, df_orders, on="customer_id", how="left")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0

In [5]:
# Right Join
pd.merge(df_customers, df_orders, on="customer_id", how="right")

   customer_id  name  order_id  amount
0            2   Bob       101     250
1            1  Adam       102     120
2            4  Dave       103     300
3            5   NaN       104     180

In [6]:
# Outer Join
pd.merge(df_customers, df_orders, on="customer_id", how="outer")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

### Concatination

In [7]:
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Adam", "Eve", "Bob"]
})
print(df1)

df2 = pd.DataFrame({
    "id": [4, 5, 6],
    "name": ["Charlie", "Fester", "Gilian"]
})
print("\n", df2)

   id  name
0   1  Adam
1   2   Eve
2   3   Bob

    id     name
0   4  Charlie
1   5   Fester
2   6   Gilian

In [11]:
# Vertically (row-wise)
pd.concat([df1, df2], ignore_index=True)

   id     name
0   1     Adam
1   2      Eve
2   3      Bob
3   4  Charlie
4   5   Fester
5   6   Gilian

In [12]:
# Horizontally (column-wise)
pd.concat([df1,df2], axis=1)

   id  name  id     name
0   1  Adam   4  Charlie
1   2   Eve   5   Fester
2   3   Bob   6   Gilian