In [40]:
import pandas as pd

### Feature Engineering

In [41]:
df = pd.read_csv("raw_data.csv").copy()
df.head(3)

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
2   2  Jane Smith   NaN  Canada  Female  62000.0

In [42]:
# apply(fn)
df["tax"] = df["income"].apply(lambda x : "20%" if x >= 60000 else "10%")
df.head(3)

   id        name   age country  gender   income  tax
0   1    John Doe  29.0     USA    Male  55000.0  10%
1   1    John Doe  29.0     USA    Male  55000.0  10%
2   2  Jane Smith   NaN  Canada  Female  62000.0  20%

In [43]:
# map()
gender_map = {"Male" : "M", "Female" : "F", "Unknown" : "U"}
df["gender"] = df["gender"].map(gender_map)
df.head(3)

   id        name   age country gender   income  tax
0   1    John Doe  29.0     USA      M  55000.0  10%
1   1    John Doe  29.0     USA      M  55000.0  10%
2   2  Jane Smith   NaN  Canada      F  62000.0  20%

In [44]:
# assign()
df = df.assign(new_income = df["income"] * 1.1)
df.head(3)

   id        name   age country gender   income  tax  new_income
0   1    John Doe  29.0     USA      M  55000.0  10%     60500.0
1   1    John Doe  29.0     USA      M  55000.0  10%     60500.0
2   2  Jane Smith   NaN  Canada      F  62000.0  20%     68200.0

In [45]:
# replace(old,new)
df["country"] = df["country"].replace("USA", "US")
df.head(3)

   id        name   age country gender   income  tax  new_income
0   1    John Doe  29.0      US      M  55000.0  10%     60500.0
1   1    John Doe  29.0      US      M  55000.0  10%     60500.0
2   2  Jane Smith   NaN  Canada      F  62000.0  20%     68200.0

In [46]:
# rename( columns={old:new} )
df = df.rename(columns = {"income":"salary"})  # rename column
print(df.head(3))

df = df.rename(index = {1:"A"})                # rename row index
print("\n", df.head(3))

df.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax", "New_Income"]  # rename entire columns
print("\n", df.head(3))

   id        name   age country gender   salary  tax  new_income
0   1    John Doe  29.0      US      M  55000.0  10%     60500.0
1   1    John Doe  29.0      US      M  55000.0  10%     60500.0
2   2  Jane Smith   NaN  Canada      F  62000.0  20%     68200.0

    id        name   age country gender   salary  tax  new_income
0   1    John Doe  29.0      US      M  55000.0  10%     60500.0
A   1    John Doe  29.0      US      M  55000.0  10%     60500.0
2   2  Jane Smith   NaN  Canada      F  62000.0  20%     68200.0

    Id        Name   Age Country Gender   Income  Tax  New_Income
0   1    John Doe  29.0      US      M  55000.0  10%     60500.0
A   1    John Doe  29.0      US      M  55000.0  10%     60500.0
2   2  Jane Smith   NaN  Canada      F  62000.0  20%     68200.0

In [47]:
# Sort
sorted_df = df.sort_values("Income")          # Sort on single column
print(sorted_df.head(3))

sorted_df = df.sort_values(["Income", "Age"]) # Sort on multiple columns
print("\n", sorted_df.head(3))

reset_df = sorted_df.reset_index()            # Create new index while preserving old
print("\n", reset_df.head(3))

reset_df = sorted_df.reset_index(drop=True)   # Create new index
print("\n", reset_df.head(3))

   Id         Name   Age Country Gender   Income  Tax  New_Income
9   9  Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
3   3         Alex   NaN      US      U  47000.0  10%     51700.0
5   5       Li Wei  27.0   China      M  51000.0  10%     56100.0

    Id         Name   Age Country Gender   Income  Tax  New_Income
9   9  Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
3   3         Alex   NaN      US      U  47000.0  10%     51700.0
5   5       Li Wei  27.0   China      M  51000.0  10%     56100.0

   index  Id         Name   Age Country Gender   Income  Tax  New_Income
0     9   9  Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
1     3   3         Alex   NaN      US      U  47000.0  10%     51700.0
2     5   5       Li Wei  27.0   China      M  51000.0  10%     56100.0

    Id         Name   Age Country Gender   Income  Tax  New_Income
0   9  Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
1   3         Alex   NaN      US      U  47000.0  10%     51700.0
2   5       Li Wei  27.0   China      M  51000.0  10%     56100.0

In [48]:
# Rank
sorted_df["Ranking"] = sorted_df["Income"].rank()  # assign rank to each new value, if tie then avg is assigned
print(sorted_df)

sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="dense")  # if tie then same rank
print("\n", sorted_df)

    Id          Name   Age Country Gender   Income  Tax  New_Income  Ranking
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0      1.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0      2.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0      3.0
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0      4.5
A    1      John Doe  29.0      US      M  55000.0  10%     60500.0      4.5
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0      6.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      7.5
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0      7.5
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0      9.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0     10.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN      NaN

     Id          Name   Age Country Gender   Income  Tax  New_Income  Ranking
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0      8.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0      7.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0      6.0
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0      5.0
A    1      John Doe  29.0      US      M  55000.0  10%     60500.0      5.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0      4.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      3.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0      3.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0      2.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0      1.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN      NaN

In [50]:
# Reordering columns
df = df[["Id", "Name", "Age", "Country", "Gender", "Tax", "Income", "New_Income"]]
df.head(3)

   Id        Name   Age Country Gender  Tax   Income  New_Income
0   1    John Doe  29.0      US      M  10%  55000.0     60500.0
A   1    John Doe  29.0      US      M  10%  55000.0     60500.0
2   2  Jane Smith   NaN  Canada      F  20%  62000.0     68200.0

### Grouping & Aggregation

In [59]:
df.groupby("Country")["Income"].count()  # Count
df.groupby("Country")["Income"].min()    # Min
df.groupby("Country")["Income"].max()    # Max
df.groupby("Country")["Income"].mean()   # Mean

Country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
US        55400.0
Name: Income, dtype: float64

In [66]:
# aggregate()
df.groupby("Country")["Income"].agg(["count", "min", "max", "mean"])
df.groupby("Country")["Income"].agg(total_count = "count", min_salary = "min", max_salary = "max", avg_salary = "mean")  # rename columns

         total_count  min_salary  max_salary  avg_salary
Country
Canada             1     62000.0     62000.0     62000.0
China              1     51000.0     51000.0     51000.0
India              1     73000.0     73000.0     73000.0
Mexico             1     45000.0     45000.0     45000.0
Spain              0         NaN         NaN         NaN
US                 5     47000.0     62000.0     55400.0

In [69]:
# aggregate on multiple columns
df.groupby("Country").agg({
    "Age" : "mean",
    "Income" : "max"
})

df.groupby("Country").agg(
    avg_age = ("Age", "mean"),
    max_salary = ("Income", "max")
)

         avg_age  max_salary
Country
Canada       NaN     62000.0
China       27.0     51000.0
India       45.0     73000.0
Mexico       NaN     45000.0
Spain       34.0         NaN
US          29.5     62000.0

### Melt & Pivot

In [ ]:
# Melt - wide to long format